### ISSUE TITLE
`OperationResponse`.`CreatedAt` and `TransactionResponse`.`CreatedAt` losing timezone info during deserialization

### ISSUE THREAD

**Issue by cuongph87** [Beans-BV/dotnet-stellar-sdk#30]
**Describe the bug**
`OperationResponse`.`CreatedAt` losing timezone info during deserialization.
For example, with definition
 `public DateTime CreatedAt { get; init; }`
and JSON value 
`"created_at": "2015-11-20T17:01:28Z",`
the deserialized string `CreatedAt` will have the value `11/20/2015 17:01:28` (no timezone).

**Note**
It seems this only happens to nested objects, for example, a JSON `TransactionResponse` object alone is deserialized correctly, while a JSON `TransactionResponse` nested inside a `PaymentOperationResponse` is not. Similarly, a `PaymentOperationResponse`, which is a child of `OperationResponse`, is not.

**Expected behavior**
The deserialized values should contain the timezone piece.

**Comment by Joviea** [comment]
TN2W4cc7a4dsYyTLiLMWa9m7jVpdLjGvYs

**Comment by Joviea** [comment]
Aki resibo mi transactions
